server.port: 8130

eureka:
  client.serviceUrl.defaultZone: http://192.168.1.158:8000/eureka
  instance:
    preferIpAddress: true

management:
  server:
    port: 8131
    ssl.enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS